### ISSUE TITLE
Experiment in Molecules

### ISSUE THREAD

**Issue by kenan12138** [zhaoyl18/SEIKO#1]
Hello, Zhao Yulai, 
Thank you very much for sharing your code for fine-tuning the diffusion model. But I noticed that this code base contains the results of fine-tuning the images and aesthetics. In your paper, Appendix D2 discusses the fine-tuning experiments on molecule generation, which does not seem to be in the existing code base. 
Can you continue to share the code related to the experiment of fine-tuning the molecular generation diffusion model? Thank you very much.

**Comment by zhaoyl18** [comment]
Hi,
   Thanks for your interest in our work. We plan to release mol experiments after images and proteins.

Best,
