### ISSUE TITLE
Bridging Model-Based Optimization and Generative Modeling via Conservative Fine-Tuning of Diffusion Models 

### ISSUE THREAD

**Issue by kenan12138** [zhaoyl18/SEIKO#2]
Hi, Zhao Yulai, I noticed that in another article Bridging Model-Based Optimization and Generative Modeling via Conservative Fine-Tuning of Diffusion Models, there seems to be no mention of the relevant code base. Can you also share the code of this article? Thank you very much.

**Comment by zhaoyl18** [comment]
Thanks for being attentive to our work. As that paper is under review, we will release the code later.
